apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-bis
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClassNamebis | quote }}
  capacity:
    storage: {{ .Values.persistence.storagebis | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:
    path: "/mnt/init"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  capacity:
    storage: {{ .Values.persistence.storage | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  hostPath:
    path: "/mnt/data"
---
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-script
spec:
  storageClassName: {{ .Values.persistence.storageClassNamebis | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizebis | quote }}
{{- end }}
---
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
