apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-bis
  labels:
    type: local
spec:
  storageClassName: manual-bis
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/init"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-script
spec:
  storageClassName: manual-bis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 73Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
