apiVersion: v1
kind: Service
metadata:
  name: mysql-demo-db
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-demo-db
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
        - name: init-script-fetch
          image: appropriate/curl
          args: ["-o", "/tmp/data/0.sql", "https://raw.githubusercontent.com/bmutziu/Portal/v0.1-alpha/scripts/MDB.sql"]
          volumeMounts:
            - name: init-script
              mountPath: /tmp/data
      containers:
        - image: mysql:5.7
          name: mysql-demo-db-1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: t00r
            - name: MYSQL_DATABASE
              value: MDB
            - name: MYSQL_USER
              value: nodejs
            - name: MYSQL_PASSWORD
              value: nodejs
          args:
            - --default-authentication-plugin=mysql_native_password
            - --lower_case_table_names=1
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysqldata
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          persistentVolumeClaim:
            claimName: init-script
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-pv-claim
