apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: portal-demo-app          # Unique name of the resource
spec:
  type: ClusterIP                 # Expose the Pods by opening a port on each Node and proxying it to the service.
  ports:                         # Take incoming HTTP requests on port 3000 and forward them to the targetPort of 3000
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: portal-demo-app            # Map any pod with label `app=portal-demo-app` to this service
